
name: dna-annotate
description: A Github action to annotate problematic sequences from given Genbank file.
inputs:
    input-dir:  # id of input
        description: 'Directory with all genbank to be read and annotated'
        required: true
        default: 'input'
    input-pattern:
        description: 'User-specified pattern to select specific files from the input directory'
        required: true
        default: '.*\.\(gb\|gbk\)'
    output-dir:
        description: 'Directory where all genbank annotated will be written'
        required: true
        default: 'output'
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.input-dir     }}
        - ${{ inputs.output-dir    }}
        - ${{ inputs.input-pattern }}
author: Friendzymes Team
branding:
    icon:  'layers'
    color: 'purple'
