
name: dna-annotator
description: A Github action to annotate problematic sequences from given Genbank file.
inputs:
    inputDir:  # id of input
        description: 'Directory with all genbank to be read and annotated'
        required: true
        default: 'input'
    outputDir:
        description: 'Directory where all genbank annotated will be written'
        required: true
        default: 'output'
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.inputDir }} ${{ inputs.outputDir }}

author: Friendzymes Team
branding:
      icon: 'layers'
      color: 'purple'
