name: main 
on:
  push:
  
jobs: 
  test: 
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
      options: --user 1001
    steps: 
    - uses: actions/checkout@v2
    - uses: Open-Science-Global/annotator@v0.5.9
    - run: find | sed 's|[^/]*/|- |g'
    - uses: actions/upload-artifact@v2
      with:
        name: annotated-sequences
        path: output/
